apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs_policy_service_actions_deployment
  labels:
    app: rs_policy_service_actions
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rs_policy_service_actions
  template:
    metadata:
      labels:
        app: rs_policy_service_actions
    spec:
      containers:
      - name: rs_policy_service_actions
        image: indikak2005/rs_policy_service_actions:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: rs_policy_service_actions
spec:
  selector:
    app: rs_policy_service_actions
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

    
  
